// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwvY-Aalmk4iL2CYitMJ8-4-vVm8MkDLI',
    appId: '1:180381835624:web:edba72b375c2256b2076dd',
    messagingSenderId: '180381835624',
    projectId: 'absenkpukepri',
    authDomain: 'absenkpukepri.firebaseapp.com',
    storageBucket: 'absenkpukepri.firebasestorage.app',
    measurementId: 'G-G8STWN9T5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb6_rwtQ9ske6M-koUI_wRbovvRGW8E8g',
    appId: '1:180381835624:android:2a4d681bdef961eb2076dd',
    messagingSenderId: '180381835624',
    projectId: 'absenkpukepri',
    storageBucket: 'absenkpukepri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCshaZ3gspSMzEy-vfl736k0ovp1YeaDmY',
    appId: '1:180381835624:ios:b71dda791aff98f12076dd',
    messagingSenderId: '180381835624',
    projectId: 'absenkpukepri',
    storageBucket: 'absenkpukepri.firebasestorage.app',
    iosBundleId: 'com.example.absenkpukepri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCshaZ3gspSMzEy-vfl736k0ovp1YeaDmY',
    appId: '1:180381835624:ios:b71dda791aff98f12076dd',
    messagingSenderId: '180381835624',
    projectId: 'absenkpukepri',
    storageBucket: 'absenkpukepri.firebasestorage.app',
    iosBundleId: 'com.example.absenkpukepri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwvY-Aalmk4iL2CYitMJ8-4-vVm8MkDLI',
    appId: '1:180381835624:web:cbe78d8930705bc42076dd',
    messagingSenderId: '180381835624',
    projectId: 'absenkpukepri',
    authDomain: 'absenkpukepri.firebaseapp.com',
    storageBucket: 'absenkpukepri.firebasestorage.app',
    measurementId: 'G-P7Z3WCTVJD',
  );
}
